version: '2.4'

x-common-definitions: &common-definitions
  stdin_open: true
  tty: true
  volumes:
    - ${COBALT_SRC:-.}:/code/
    - ./docker/linux/scripts:/scripts
    - ${COBALT_SRC:-.}/out/ccache:/root/ccache
  depends_on:
    - base

services:
  # Define common build container for Linux
  base:
    build:
      args:
        - BASE_OS
      context: ./docker/linux
      dockerfile: base/Dockerfile
    image: cobalt-build-base

  stub:
    <<: *common-definitions
    build:
      context: ./docker/linux
      dockerfile: stub/Dockerfile
    image: cobalt-build-linux-stub
    environment:
      - PLATFORM=stub
      - CONFIG=${CONFIG:-debug}

  linux-x64x11:
    <<: *common-definitions
    build:
      context: ./docker/linux
      dockerfile: linux-x64x11/Dockerfile
    image: cobalt-build-linux
    environment:
      - PLATFORM=linux-x64x11
      - CONFIG=${CONFIG:-debug}

  # Define common build container for Evergreen
  build-evergreen:
    <<: *common-definitions
    build:
      context: ./docker/linux
      dockerfile: evergreen/Dockerfile
    image: cobalt-build-evergreen
    environment:
      - PLATFORM
      - CONFIG

  evergreen-x64-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-x64-sbversion-12

  evergreen-x86-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-x86-sbversion-12

  evergreen-arm64-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-arm64-sbversion-12

  evergreen-arm-hardfp-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-arm-hardfp-sbversion-12

  evergreen-arm-softfp-sbversion-12:
    <<: *common-definitions
    image: cobalt-build-evergreen
    depends_on: [ build-evergreen ]
    environment:
      - PLATFORM=evergreen-arm-softfp-sbversion-12
